const data = [{
    "CategoryName": "GMC",
    "CreatedAt": "12/11/2022",
    "condtion": true,
    "_id": "#2fb"
  }, {
    "CategoryName": "MINI",
    "CreatedAt": "04/25/2023",
    "condtion": false,
    "_id": "#945"
  }, {
    "CategoryName": "Ford",
    "CreatedAt": "09/24/2022",
    "condtion": true,
    "_id": "#cef"
  }, {
    "CategoryName": "Mitsubishi",
    "CreatedAt": "09/20/2022",
    "condtion": false,
    "_id": "#f9a"
  }, {
    "CategoryName": "Mercedes-Benz",
    "CreatedAt": "12/12/2022",
    "condtion": true,
    "_id": "#84e"
  }, {
    "CategoryName": "Mitsubishi",
    "CreatedAt": "04/09/2023",
    "condtion": true,
    "_id": "#374"
  }, {
    "CategoryName": "BMW",
    "CreatedAt": "08/02/2023",
    "condtion": false,
    "_id": "#810"
  }, {
    "CategoryName": "Mercury",
    "CreatedAt": "03/22/2023",
    "condtion": true,
    "_id": "#56a"
  }, {
    "CategoryName": "Subaru",
    "CreatedAt": "06/24/2023",
    "condtion": false,
    "_id": "#a6b"
  }, {
    "CategoryName": "Audi",
    "CreatedAt": "10/23/2022",
    "condtion": false,
    "_id": "#803"
  }]
export default data